### PR TITLE
Replace Travis CI with GitHub Actions

### LINKED ISSUE #168: Move to GitHub Actions
**Is your feature request related to a problem? Please describe.**

Travis CI is limited in what types of emulators it can run. GitHub Actions are not.

This feedback relates to:
- [x] The Kotlin library
- [x] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [x] The sample code
- [ ] The documentation

**Describe the solution you'd like**

Move the Library, Gradle Plugin and Sample tests to GitHub Actions.

### PR DESCRIPTION
**Pull request by DanielJette**
### What does this change accomplish?

Resolves #168 

Replace Travis CI with GitHub Actions

⚠️ Note: Requires #167 to be merged first.

### How have you achieved it?

Migrate the existing Travis CI checks to GitHub workflows.

New workflows:

- [Sample](https://github.com/Shopify/android-testify/actions?query=workflow%3A%22Build+Sample%22)
- [Gradle Plugin](https://github.com/Shopify/android-testify/actions?query=workflow%3A%22Build+Gradle+Plugin%22)
- [Library](https://github.com/Shopify/android-testify/actions?query=workflow%3A%22Build+Library%22)

Also upgraded the baseline and test emulator to API 29.

### Notice

This change must keep `master` in a shippable state; **it may be shipped without further notice**.

### CODE REVIEW

**Comment by fredells** [comment]
TIL. Github does CI

**Comment by fredells** [comment]
Two tests were `Skipped`. Is that expected?

**Comment by DanielJette** [comment]
> Two tests were Skipped. Is that expected?

I'll check. Shouldn't be

**Comment by DanielJette** [comment]
> > Two tests were Skipped. Is that expected?

> I'll check. Shouldn't be

@fredells did you mean these two?
- `Build IntelliJ Platform Plugin / Release Draft (pull_request) Skipped`
- `Build IntelliJ Platform Plugin / Release Draft (push) Skipped`

I thought you meant specific jvm/instrumentation tests. Those two actions are supposed to be skipped, yes. They are only run on commits to `master`. They draft up a release of the IntelliJ plugin for publishing.

**Comment by DanielJette** [comment]
Something's fishy with the base branch on this

**Comment by DanielJette** [comment]
Not waiting on Travis CI

**Pull request merged**
