### PR TITLE
Prepare Testify 1.0.0-beta1

### PR DESCRIPTION
**Pull request by DanielJette**
### What does this change accomplish?

This PR includes all the changes from the Shopify monorepo up to and including commit [4742ea8](https://github.com/Shopify/android/tree/4742ea8a6facf3c838b5d74d8e3eeff1ce39a66e).

### How have you achieved it?

I have used the `dev open-source` command to export the latest version from the Shopify monorepo. I have updated all the tests and dependencies to ensure a green build. This PR in and of itself is necessary, but not sufficient for 1.0.0-beta1. A future PR including additional tests and documentation is still required.

Next step will be to migrate the monorepo to this version and move all future development to the open-source repo.

### Tophat instructions

This PR includes both Library tests as well as the Sample app. Both should work appropriately on all emulators from API 19 through to API 29. Note, however, that baselines are included only for API 22 emulators compatible with Travis CI.

### CODE REVIEW

**Comment by DanielJette** [comment]
> Side note, I think we could drop the requirement of root access if it's only being used to ls the /data/data/package directory. IIRC if you know the fully qualified path (which we would) you have read access to those files.

@jaredh 
screenshotPull requires `adb root` in order to access arbitrary package directories. I added the root check with the `ls` as a quick way to verify if we already have the required access. `ls` on a `data/data` folder will fail if you don't have root, so it's an easy check.

**Comment by jaredh** [comment]
> screenshotPull requires `adb root` in order to access arbitrary package directories. I added the root check with the `ls` as a quick way to verify if we already have the required access. `ls` on a `data/data` folder will fail if you don't have root, so it's an easy check.

All of that can be accomplished with something like 

```kotlin
+    fun runAs(packageId: String): Adb {
+        arguments.add("run-as")
+        arguments.add(packageId)
+        return this
+    }
```

And changing the `adb pull` to an `exec-out cat`.

... as for the device setup that is another story. Not sure which of those props require root. Restarting zygote probably another nono. Not sure if there is a use case for running Testify on a non-rooted device/image. Just an idea 🤷‍♂️

**Comment by DanielJette** [comment]
> All of that can be accomplished with something like

Hmm... definitely hadn't considered that. I use that myself when interacting with the shell; never occurred to me to use that with Testify.
Sounds like something I should do separately, however. I don't want to bury that kind of change in what's already a huge PR. I'll hold off merging this until I fix that, however, I'll probably put up the change separately

**Comment by DanielJette** [comment]
@jaredh I've opened a PR to address the root access issue here https://github.com/Shopify/android-testify/pull/136

I'm going to merge this PR now.

**Pull request merged**
